services:
  atm_service:
    build:
      context: backend/atm_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT_ATM}:${PORT_ATM}"
    depends_on:
      - core_banking_service

  core_banking_service:
    build:
      context: backend/core_banking_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT_BANKING}:${PORT_BANKING}"

  ni_switch_service:
    build:
      context: backend/ni_switch_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT_NI}:${PORT_NI}"

  rero_web_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RECO_WEB_PORT}:80"
    depends_on:
      - atm_service
      - ni_switch_service
      - core_banking_service
